# Generated by Django 3.0 on 2020-07-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktop',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Items ready to be purchase'), ('SOLD', 'Item sold'), ('RESTOCKING', 'Restocking item in a few days')], default='Sold', max_length=10),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Items ready to be purchase'), ('SOLD', 'Item sold'), ('RESTOCKING', 'Restocking item in a few days')], default='Sold', max_length=10),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Items ready to be purchase'), ('SOLD', 'Item sold'), ('RESTOCKING', 'Restocking item in a few days')], default='Sold', max_length=10),
        ),
    ]
